services:
  - type: web
    name: job-portal
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn job_portal.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: job_portal.settings
      - key: PYTHON_VERSION
        value: 3.10
    staticPublishPath: staticfiles
