# Generated by Django 5.1.7 on 2025-03-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_rename_posted_at_job_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='company_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='current_employees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='established_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True, default='Not specified'),
        ),
    ]
