# Generated by Django 5.1.7 on 2025-03-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_company_remove_recruiter_company_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='company_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='hr_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
