# Generated by Django 5.1.6 on 2025-04-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recruiter_company_address_recruiter_company_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('fresher', 'Fresher'), ('experienced', 'Experienced')], default='fresher', max_length=15),
        ),
    ]
