# Generated by Django 5.0.6 on 2025-04-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='company_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
